cfg:
  mlflow:
    tracking_uri: http://127.0.0.1:8080
  export:
    onnx_path: triton/export/onnx/model.onnx
    fp16: true
  checkpoint:
    dirpath: ./checkpoints
  model_path: ./checkpoints/best_model_weights.pth
  image_path: ./infer_images/sm.PNG
  threshold: 0.5
  model:
    _target_: models.vit_model.ViTModel
    model_name: WinKawaks/vit-tiny-patch16-224
    id2label:
      0: not_smoking
      1: smoking
    label2id:
      not_smoking: 0
      smoking: 1
  data:
    data_dir: data
    batch_size: 64
    num_workers: 8
    image_size: 224
    class_names:
    - notsmoking
    - smoking
    augment: true
  trainer:
    max_epochs: 4
    devices: 1
    logger:
      _target_: pytorch_lightning.loggers.TensorBoardLogger
      save_dir: logs/
      name: smooking_detection
  optimizer:
    _target_: torch.optim.AdamW
    lr: 5.0e-07
    betas:
    - 0.9
    - 0.999
    eps: 1.0e-08
    weight_decay: 0.02
